### ISSUE TITLE
provision.xml - is full GAV needed

### ISSUE THREAD

**Issue by rsvoboda** [wildfly/wildfly-galleon-pack-template#3]
In example provision.xml WF uses alias `wildfly@maven(org.jboss.universe:community-universe):current`

But template-galleon-pack uses full GAV
https://github.com/wildfly/wildfly-galleon-pack-template/blob/master/provision.xml#L32

Is there a way to specify that custom pack in shorter way ?

```
location="org.wildfly.extras.galleon-feature-pack-template:template-galleon-pack:1.0.0.Alpha-SNAPSHOT"
```
```
location="org.wildfly.extras.galleon-feature-pack-template:template-galleon-pack:"

location=":template-galleon-pack:"

location="template-galleon-pack"
```

**Comment by kabir** [comment]
I think it is not possible since I have not added it to a universe. In https://github.com/wildfly/wildfly-galleon-pack-template/blob/master/galleon-pack/wildfly-feature-pack-build.xml I changed the 'producer' to be the GA of the maven project since @jfdenise pointed out it was not part of a universe (I originally had some kind of thing based on the producer values from the WildFly feature packs).

I have no idea what is involved in creating a universe. And perhaps that is confusing to users for this introduction? Maybe once I have a better idea of what a universe is, I (or someone else) could do  a follow up blog post about universes, where we have another branch which adds a few commits to this one?

**Comment by jfdenise** [comment]
Full GAV must be used in this case, there is no universe. Universe adds an extra level of complexity, we shouldn't force users to create universe/producer when building their own galleon feature-pack.

**Comment by rsvoboda** [comment]
> Full GAV must be used in this case

Would it be possible to enhance Galleon to support GA or just artifactId? 

For Quarkus add-extension users do not need to specify full GA, they can specify artifactId or just part of the artifactId. If there is only one match to that string, extension is added, otherwise no match / multiple matches error is reported to the user. 

Something similar could be handy for galleon too.

**Comment by jfdenise** [comment]
I think @aloubyansky is working on making GA more handy.

**Comment by aloubyansky** [comment]
The answer to that is to register a producer.
Quarkus analogy is actually not that different. You provide a keyword that will be looked up in a registry of extensions. If you create your own extension and deploy it to maven it won't be magically appearing in Quarkus tooling until you register it in the Quarkus universe/platform.
In Galleon world there is a universe which is a registry of producers.

**Comment by kabir** [comment]
Closing as I don't think this belongs here
